Dieses Repository beinhaltet die Unterlagen zum Workshop 04

"Continuous Delivery - Hands on"

an den CH OPEN Workshoptagen. Dieser Workshop findet am 09.09.2014 statt.

Alle Informationen über den Workshop und den Workshoptagen sind auf der Webseite der
http://www.ch-open.ch/wstage/workshop-tage/programm-2014/ws-4-continuous-delivery-hands-on/[ch open] zu finden.

Im Workshop arbeiten wir mit http://xubuntu.org/[Xubuntu] innerhalb von https://www.virtualbox.org/[VirtualBox].

== Vorbereitung auf den Workshop
=== Installation des Images

Voraussetzung zum Benutzen des Image ist eine https://www.virtualbox.org/wiki/Downloads[VirtualBox Installation] auf dem
eigenen Laptop.

==== Installation via Vagrant

Die einfachste Art das Image zu installieren ist via http://www.vagrantup.com/downloads.html[Vagrant].

Dazu geht man wie folgt vor:

* installiere Vagrant http://www.vagrantup.com/downloads.html
* copiere die Datei https://github.com/ollin/cd-ws-p.git/vagrant/Vagrantfile auf den Rechner
  ** via +git clone https://github.com/ollin/cd-ws-p.git+
  ** via +wget https://raw.githubusercontent.com/ollin/cd-ws-p/master/vagrant/Vagrantfile -P cd-ws-p/vagrant+
  ** via Browser https://raw.githubusercontent.com/ollin/cd-ws-p/master/vagrant/Vagrantfile
     *** speichere die Datei unter gleichem Namen in einem Verzeichnis "cd-ws-p/vagrant"
* wechsle ins Verzeichnis "cd-ws-p/vagrant"
* starte mit +vagrant up+
  ** es erfolgt nun der Download der Box (~3.5GB)
  ** die Box wird nun als Guest Machine in VirtualBox erzeugt und gestartet

== VirtualBox Image

VirtualBox 4.3.10

Das Image ist wie folgt konfiguriert:

- CPU's:    2
- RAM:      3072 MB
- HD:       20GB , dynamisch, LVM
- Network:  Bridged Adapter

Das Image enthaelt:

- Xubuntu 14.04 Desktop 64bit
- VirtualBox Guest Additions

- Docker 1.1.1
- Oracle JDK 8 "1.8.0_05"
- Git 1.9.1
- Firefox 30.0
- Chromium 39.0 (Linux-Variante von Chrome)
- Intellij Idea Community Edition 13.1
- Jenkins ver. 1.565.1 ( http://localhost:8180 )
- Nexus-2.8.1-01 OS ( http://localhost:8181/nexus )
- ssh server (für vagrant)

== Links

http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

___
Oliver Nautsch.



