---
  - name: Install docker dependencies
    apt: state=installed pkg={{ item }}
    with_items: "{{ docker_required_packages }}"

  - name: Install docker repo key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

  - name: Install docker
    apt: state=installed pkg=docker-ce

  - name: Start docker service
    service: name=docker state=started

  - name: Add users to group docker
    user: name={{ item }} groups=docker append=true
    with_items: "{{ docker_users }}"

  - name: Change /etc/default/docker
    template:
      src={{role_path}}/templates/docker.j2
      dest=/etc/default/docker
      mode="u=rw,g=r,o=r"
    notify:
      - restart docker
