# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.4"

Vagrant.configure("2") do |config|

  #config.vm.box = "ubuntu/xenial64" # problem is it exports UART with hardcoded path for logging via serial port see https://bugs.launchpad.net/cloud-images/+bug/1627844
  #config.vm.box = "boxcutter/ubuntu1604" nicht mehr so aktuell
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.box_check_update = true

  config.vm.synced_folder ".", "/vagrant/"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "cd-ws-box"
    vb.memory = 8192
    vb.cpus = 4
    # vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.define 'devcompi' do |machine|

    machine.vm.provision :ansible_local do |ansible|
        ansible.playbook          = "playbook.yml"
        ansible.galaxy_role_file  = "requirements.yml"
        ansible.verbose           = true
        ansible.install           = true
        ansible.limit             = "devcompi"
        ansible.inventory_path    = "inventory"
    end
  end
end
