== Iteration 10 - stage-integration

Annahme::

* Integrationstest benutzt Docker Image (bisher extra Verticle gestartet)
* die Integrationsumgebung wird unter Port 8071 erreichbar sein

Schritte::

* kopiere die +stage-production/build.gradle+ nach +stage-integration/build.gradle+
* kopiere die +stage-production/gradle.properties+ nach +stage-integration/gradle.properties+
* ersetze den String "production" mit "integration" und "Production" mit "Integration"
* benutze für den Container den port 8071 (parent -> child, 8071:8080)
* benutze das _java_ Plugin in gradle
* füge als Repository +mavenCentral()+ ein
* füge folgende Abhängigkeiten ein
----
  testCompile "io.vertx:vertx-core:$vertxVersion"
  testCompile "io.vertx:vertx-platform:$vertxVersion"
  testCompile "junit:junit:$junitVersion"
  testCompile "io.vertx:testtools:$toolsVersion"
----
* mache den Task _test_ abhängig von _deployIntegration_ (+./gradle --dry-run test+ zeigt die Abarbeitungsfolge)
* verschiebe den Test +IssuesViaRestTest+ in dieses Projekt
* Entferne die Initialisierung von +IssuesStarterVerticle+ aus dem Test
* füge einen Jenkins Job _issumy-stage-integration_ zwischen _stage-commit_ und _stage-production_ ein
  ** Umgebungsvariablen nicht vergessen!
  ** automatisch starten nach commit

== Iteration 10 - stage-integration - Diskussion

* Warum kein Unterprojekt im Sinne von gradle?
* Haben wir bisher einen Abbruch in der Pipeline, wenn etwas nicht funktioniert?
* Haben wir bisher Unit Tests?


