---
  - name: Clone cd-ws-address project
    git:
      repo: 'https://github.com/ollin/cd-ws-address.git'
      dest: '/home/dev/cd-ws-address'

  - name: Set permissions to user dev
    file:
      path: '/home/dev/cd-ws-address'
      recurse: yes
      group: dev
      owner: dev

  - name: build project to download files
    command: su dev -c './gradlew build clean'
    args:
      chdir: /home/dev/cd-ws-address/handson-01

  - name: download root gradle infra
    command: su dev -c './gradlew sync01'
    args:
      chdir: /home/dev/cd-ws-address

  - name: mv .gradle from root (workaround for non-privileged user)
    command:  mv /root/.gradle /home/dev/.gradle
    args:
      creates: "/home/dev/.gradle"
      removes: "/root/.gradle"

  - name: Set permissions of /home/dev/.gradle to user dev (workaround for non-privileged user)
    file:
      path: '/home/dev/.gradle'
      recurse: yes
      group: dev
      owner: dev










